# docker-compose -p gsaopenstudioshowcase up

version: "3.3"
services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsaopenstudioshowcase
      MYSQL_USER: gsaopenstudioshowcase
      MYSQL_PASSWORD: gsaopenstudioshowcase
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    volumes:
      - gsaopenstudioshowcase_db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
      - ./mariadb-conf:/etc/mysql/mariadb.conf.d
  
  nginx:
    depends_on:
      - db
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../www:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d

  fpm:
    build:
      context: ./fpm
    env_file:
      - ./fpm/vars.env
    volumes:
      - ../www:/var/www/html
      - ./fpm-conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini

volumes:
    gsaopenstudioshowcase_db_data:
    gsaopenstudioshowcase_db_data_2020:
    gsaopenstudioshowcase_db_data_2021:
